@echo off
echo Installing dependencies...
call npm install
echo Generating Prisma client...
call npx prisma generate
echo Pushing schema to database...
call npx prisma db push --accept-data-loss
echo Seeding database...
call node prisma\seed.js
echo Starting dev server...
call npm run dev
